# Nom du service
quarkus.application.name=meeting-service

# Désactiver DevServices (empêche Quarkus de lancer Docker)
quarkus.devservices.enabled=false
quarkus.datasource.devservices.enabled=false
quarkus.rabbitmq.devservices.enabled=false

# Base de données mysql locale
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/meetingdb

# Hibernate : créer ou mettre à jour les tables automatiquement
quarkus.hibernate-orm.database.generation=update

# Swagger / OpenAPI
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/openapi

# Port HTTP
quarkus.http.port=8081
