# Meeting service datasource configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=meeting
quarkus.datasource.password=${MEETING_DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/Meeting
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.jdbc.max-size=16
quarkus.http.root-path=/
quarkus.rabbitmq.devservices.enabled=false
